config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.draw do
    namespace :api do
      namespace :v1 do
        resources :devices, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end
  root 'dashboard#index' 
  
  get '/registers', to: 'register#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :restaurant
  has_many :registers, dependent: :destroy

  after_save :create_register
  after_destroy :delete_status_device
  validates :name, presence: true
  validates :status, presence: true

  validates :status, presence: true, inclusion: { in: %w(maintenance active), message: "%{value} no es válido para status" }
  

  private
    def create_register
      Register.create(device: self, status: self.status)
    end

    def delete_status_device
      Register.create(device: self, status: "deleted")
    end
end

app/models/register.rb
class Register < ApplicationRecord
  belongs_to :device
  validates :status, presence: true

  def restaurant_name
    device.restaurant.name
  end
end  

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :devices, dependent: :destroy
    validates :name, presence: true
    validates :status, presence: true
end

app/controllers/api/v1/devices_controller.rb
module Api
    module V1
      class DevicesController < ApplicationController
        skip_before_action :verify_authenticity_token

        before_action :set_device, only: [:update, :destroy]
        after_action :update_restaurant_status, only: [:create, :update]
        # POST /api/v1/devices
        def create
            @device = Device.new(device_params)
            if @device.save
                render json: @device, status: :created
            else
                render json: @device.errors, status: :unprocessable_entity
            end
        end
        # PATCH/PUT /api/v1/devices/:id
        def update
          if @device.update(device_params)
            render json: @device
          else
            render json: @device.errors, status: :unprocessable_entity
          end
        end

        # DELETE /api/v1/devices/:id
        def destroy
            @device.destroy
            render json: { message: 'Device deleted' }
        end
  
        private
          
          def set_device
            @device = Device.find(params[:id])
          end
    
          def device_params
              params.require(:device).permit(:name, :status, :restaurant_id)
          end

          def update_restaurant_status
            UpdateRestaurantStatusJob.perform_async(@device.restaurant_id)
          end
      end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
        @restaurants = Restaurant.all
        @devices = @restaurants.map(&:devices).flatten
    end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
    def index
        @registers = Register.all        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1>Lista de Restaurantes</h1>

<% if @restaurants.any? %>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Estado</th>
      </tr>
    </thead>
    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td><%= restaurant.name %></td>
            <td class="<%= restaurant.status == 'operativo' ? 'text-success' : restaurant.status == 'warning'  ? 'text-warning' : restaurant.status == 'problema'  ? 'text-danger': '' %>">
            <%= restaurant.status %>
            </td>        
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No hay dispositivos disponibles.</p>
<% end %>

<h1>Lista de dispositivos por Restaurant</h1>

<% if @devices.any? %>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Restaurant</th>
        <th scope="col">Nombre</th>
        <th scope="col">Estado</th>
      </tr>
    </thead>
    <tbody>
      <% @devices.each do |device| %>
        <tr>
          <td><%= device.restaurant.name %></td>
          <td><%= device.name %></td>
            <td class="<%= device.status == 'active' ? 'text-success' : device.status == 'maintenance' ? 'text-danger' : '' %>">
            <%= device.status %>
            </td>        
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No hay dispositivos disponibles.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Niufoods</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Niufoods</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Registro de mantenimiento', registers_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Dashboard', root_path, class: 'nav-link' %>
            </li>            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/register/index.html.erb
<h1>Lista de registros de mantenimiento</h1>

<% if @registers.any? %>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Restaurant</th>
        <th scope="col">Nombre Dispositivo</th>
        <th scope="col">Estado</th>
      </tr>
    </thead>
    <tbody>
      <% @registers.each do |register| %>
        <tr>
          <td><%= register.restaurant_name %></td>
          <td><%= register.device.name %></td>
            <td class="<%= register.status == 'active' ? 'text-success' : register.status == 'maintenance' ? 'text-danger' : '' %>">
            <%= register.status %>
            </td>        
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No hay dispositivos disponibles.</p>
<% end %>